platform: linux
image_resource:
  type: docker-image
  source: {repository: maven}
params:
  _JAVA_OPTIONS: "-Djdk.net.URLClassPath.disableClassPathURLCheck=true"
inputs:
  - name: maven-test
run:
  path: mvn
  args: [clean package]
  dir: maven-test
